import { HttpStatus } from '@nestjs/common';

export const ErrorCode = {
  VALIDATION_FAILED: HttpStatus.BAD_REQUEST,
  UNAUTHORIZED: HttpStatus.UNAUTHORIZED,
  INVALID_CREDENTIALS: HttpStatus.UNAUTHORIZED,
  FORBIDDEN: HttpStatus.FORBIDDEN,
  PHONE_NOT_VERIFIED: HttpStatus.FORBIDDEN,
  ACCOUNT_SUSPENDED: HttpStatus.FORBIDDEN,
  ACCOUNT_LOCKED: HttpStatus.LOCKED,
  NOT_FOUND: HttpStatus.NOT_FOUND,
  CONFLICT: HttpStatus.CONFLICT,
  RATE_LIMITED: HttpStatus.TOO_MANY_REQUESTS,

  OTP_INVALID: HttpStatus.BAD_REQUEST,
  OTP_EXPIRED: HttpStatus.BAD_REQUEST,
  OTP_ATTEMPTS_EXCEEDED: HttpStatus.TOO_MANY_REQUESTS,
  OTP_COOLDOWN: HttpStatus.TOO_MANY_REQUESTS,

  PIN_NOT_SET: HttpStatus.FORBIDDEN,
  PIN_INVALID: HttpStatus.FORBIDDEN,
  PIN_LOCKED: HttpStatus.LOCKED,
  PIN_TOO_WEAK: HttpStatus.BAD_REQUEST,

  KYC_INVALID_TARGET_TIER: HttpStatus.UNPROCESSABLE_ENTITY,
  KYC_SUBMISSION_PENDING: HttpStatus.CONFLICT,

  WALLET_EXISTS: HttpStatus.CONFLICT,
  WALLET_NOT_ACTIVE: HttpStatus.UNPROCESSABLE_ENTITY,
  WALLET_NOT_EMPTY: HttpStatus.UNPROCESSABLE_ENTITY,
  CURRENCY_NOT_PERMITTED: HttpStatus.UNPROCESSABLE_ENTITY,
  LIMIT_EXCEEDED: HttpStatus.UNPROCESSABLE_ENTITY,
  INSUFFICIENT_FUNDS: HttpStatus.UNPROCESSABLE_ENTITY,
  INVALID_AMOUNT: HttpStatus.BAD_REQUEST,
  SELF_TRANSFER: HttpStatus.UNPROCESSABLE_ENTITY,

  QUOTE_EXPIRED: HttpStatus.UNPROCESSABLE_ENTITY,
  QUOTE_ALREADY_EXECUTED: HttpStatus.CONFLICT,

  LEDGER_UNBALANCED: HttpStatus.UNPROCESSABLE_ENTITY,
  LEDGER_INVALID_ENTRY: HttpStatus.UNPROCESSABLE_ENTITY,
  ENTRY_ALREADY_REVERSED: HttpStatus.CONFLICT,
  CONCURRENT_MODIFICATION: HttpStatus.CONFLICT,

  IDEMPOTENCY_KEY_REQUIRED: HttpStatus.BAD_REQUEST,
  IDEMPOTENCY_KEY_INVALID: HttpStatus.BAD_REQUEST,
  IDEMPOTENCY_KEY_REUSED: HttpStatus.UNPROCESSABLE_ENTITY,
  IDEMPOTENCY_IN_PROGRESS: HttpStatus.CONFLICT,

  // ── phase 2 ──
  USERNAME_TAKEN: HttpStatus.CONFLICT,
  CURRENCY_MISMATCH: HttpStatus.UNPROCESSABLE_ENTITY,
  INVALID_STATE_TRANSITION: HttpStatus.CONFLICT,
  PAYMENT_REQUEST_NOT_PENDING: HttpStatus.CONFLICT,
  PAYMENT_REQUEST_EXPIRED: HttpStatus.UNPROCESSABLE_ENTITY,
  QR_INVALID: HttpStatus.BAD_REQUEST,
  QR_EXPIRED: HttpStatus.UNPROCESSABLE_ENTITY,
  QR_ALREADY_PAID: HttpStatus.CONFLICT,
  QR_NOT_ACTIVE: HttpStatus.UNPROCESSABLE_ENTITY,
  QR_PREVIEW_INVALID: HttpStatus.BAD_REQUEST,
  QR_PREVIEW_EXPIRED: HttpStatus.UNPROCESSABLE_ENTITY,
  QR_PREVIEW_USED: HttpStatus.CONFLICT,
  MERCHANT_EXISTS: HttpStatus.CONFLICT,
  MERCHANT_NOT_ACTIVE: HttpStatus.UNPROCESSABLE_ENTITY,
  PAYMENT_NOT_REFUNDABLE: HttpStatus.UNPROCESSABLE_ENTITY,
  REFUND_EXCEEDS_PAYMENT: HttpStatus.UNPROCESSABLE_ENTITY,
  WEBHOOK_SIGNATURE_INVALID: HttpStatus.UNAUTHORIZED,
  FEATURE_DISABLED: HttpStatus.NOT_FOUND,
  PAYMENT_FAILED: HttpStatus.UNPROCESSABLE_ENTITY,

  INTERNAL: HttpStatus.INTERNAL_SERVER_ERROR,
} as const;

export type ErrorCode = keyof typeof ErrorCode;

export const isErrorCode = (value: unknown): value is ErrorCode =>
  typeof value === 'string' && Object.prototype.hasOwnProperty.call(ErrorCode, value);

/** An expected, business-level failure with a stable machine-readable code. */
export class DomainError extends Error {
  readonly status: number;

  constructor(
    readonly code: ErrorCode,
    message: string,
    readonly details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = 'DomainError';
    this.status = ErrorCode[code];
  }
}
